apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: busybox-replica
  labels:
    app: my-first-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: busybox
        image: busybox
