apiVersion: v1
kind: Pod
metadata:
  name: print-envars-greeting
  labels:
    name: greeting
spec:
  containers:
    - name: nginx-img
      image: bash
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      command: ["echo", "$(GREETING) $(COMPANY) $(GROUP)!!"]
      env:
        - name: GREETING
          value: "Welcome to"
        - name: COMPANY
          value: "DevOps"
        - name: GROUP
          value: "Industries"
