apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    name: multi-container
spec:
  containers:
    - name: gold
      image: redis
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  initContainers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "echo Sleep && sleep 200"]
