apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  labels:
    select: pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /pv/log 
