apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  selector:
    matchLabels:
        select: pv
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  # storageClassName: ""   
  accessModes:
    - ReadWriteMany
  
