apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    name: conf-map
spec:
  containers:
    - name: webapp-color
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      envForm:
        - configMapRef:
            name: webapp-config-map
