apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/log/nginx
        name: nginx-log-volume
  volumes:
    - name: nginx-log-volume
      persistentVolumeClaim:
        claimName: claim-log-1