apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: nginx
    tier: backend
spec:
  containers:
    - name: nginx-pod
      image: nginx:alpine
      ports:
        - containerPort: 80
