apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: nginx
    tier: backend
spec:
  containers:
    - name: nginx-pod
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
